### ISSUE TITLE
Fehlende inhalte

### ISSUE THREAD

**Issue by Nachtpfoetchen** [xaverW/ATPlayer#1]
Sehr cooles tool, allerdings scheinen mir manche inhalte der Audiothek zu fehlen. Ich finde nicht die thriller höhrspiele unter: https://www.ardaudiothek.de/sendung/knallhart-die-ard-thriller-hoerspiele/33514844/
in der applikation.

**Comment by xaverW** [comment]
da hat sich die Website der Audiothek geändert, bin dran das anzupassen


Am Tue, 22 Oct 2024 15:04:33 -0700
schrieb nachtpfoetchen ***@***.***>:

> Sehr cooles tool, allerdings scheinen mir manche inhalte der
> Audiothek zu fehlen. Ich finde nicht die thriller höhrspiele
> unter: https://www.ardaudiothek.de/sendung/knallhart-die-ard-thriller-hoerspiele/33514844/ in der applikation.
>

**Comment by xaverW** [comment]
schaus dir mal an, sollte wieder passen.

**Comment by Nachtpfoetchen** [comment]
Super! Danke sehr fürs fixen, bei mir funktioniert es :)
